version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker # Dockerfile base image and syntax digests
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
